"""Scoring and analysis models — deterministic ranking outputs."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ScoreComponents(BaseModel):
    """Individual components that feed the overall score.

    All values are 0.0–1.0 *before* weighting.
    """

    model_config = ConfigDict(strict=True)

    spec_fit: float = Field(default=0.0, ge=0.0, le=1.0)
    value: float = Field(default=0.0, ge=0.0, le=1.0)
    delivery: float = Field(default=0.0, ge=0.0, le=1.0)
    condition: float = Field(default=0.0, ge=0.0, le=1.0)
    trust: float = Field(default=0.0, ge=0.0, le=1.0)


class Analysis(BaseModel):
    """Deterministic ranking output attached to each search result.

    ``overall_score`` is the weighted sum of the components.
    ``explanation`` is generated by the explanation agent *after* scoring.
    """

    model_config = ConfigDict(strict=True)

    components: ScoreComponents = ScoreComponents()
    overall_score: float = Field(default=0.0, ge=0.0, le=1.0)
    explanation: str = ""
    watch_trigger_reason: str | None = None
